version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: chatgouser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatgo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped  # redémarre automatiquement si crash

  notebook:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:


# ce fichier permettra de lancer toute l'app automatiquement sans rien configurer : docker-compose up -d